/*----- PROTECTED REGION ID(TemperatureSensorClass.h) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        TemperatureSensorClass.h
//
// description : Include for the TemperatureSensor root class.
//               This class is the singleton class for
//                the TemperatureSensor device class.
//               It contains all properties and methods which the
//               TemperatureSensor requires only once e.g. the commands.
//
// project :     TemperatureSensor
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TemperatureSensorClass_H
#define TemperatureSensorClass_H

#include <tango/tango.h>
#include "TemperatureSensor.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	TemperatureSensorClass.h


namespace TemperatureSensor_ns
{
/*----- PROTECTED REGION ID(TemperatureSensorClass::classes for dynamic creation) ENABLED START -----*/
/* clang-format on */

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	TemperatureSensorClass::classes for dynamic creation

//=========================================
//	Define classes for attributes
//=========================================
//	Attribute Temperature class definition
class TemperatureAttrib: public Tango::Attr
{
public:
	TemperatureAttrib():Attr("Temperature",
			Tango::DEV_DOUBLE, Tango::READ) {}
	~TemperatureAttrib() {}
	virtual void read(Tango::DeviceImpl *dev,Tango::Attribute &att)
		{(static_cast<TemperatureSensor *>(dev))->read_Temperature(att);}
	virtual bool is_allowed(Tango::DeviceImpl *dev,Tango::AttReqType ty)
		{return (static_cast<TemperatureSensor *>(dev))->is_Temperature_allowed(ty);}
};


//=========================================
//	Define classes for commands
//=========================================
//	Command Reset class definition
class ResetClass : public Tango::Command
{
public:
	ResetClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out,
				   const char        *in_desc,
				   const char        *out_desc,
				   Tango::DispLevel  level)
	:Command(cmd_name,in,out,in_desc,out_desc, level)	{}

	ResetClass(const char   *cmd_name,
	               Tango::CmdArgType in,
				   Tango::CmdArgType out)
	:Command(cmd_name,in,out)	{}
	~ResetClass() {}

	virtual CORBA::Any *execute (Tango::DeviceImpl *dev, const CORBA::Any &any);
	virtual bool is_allowed (Tango::DeviceImpl *dev, const CORBA::Any &any)
	{return (static_cast<TemperatureSensor *>(dev))->is_Reset_allowed(any);}
};


/**
 *	The TemperatureSensorClass singleton definition
 */

#ifdef _TG_WINDOWS_
class __declspec(dllexport)  TemperatureSensorClass : public Tango::DeviceClass
#else
class TemperatureSensorClass : public Tango::DeviceClass
#endif
{
	/*----- PROTECTED REGION ID(TemperatureSensorClass::Additional DServer data members) ENABLED START -----*/
	/* clang-format on */
	//	Add your own code
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	TemperatureSensorClass::Additional DServer data members

	public:
		//	write class properties data members
		Tango::DbData	cl_prop;
		Tango::DbData	cl_def_prop;
		Tango::DbData	dev_def_prop;
		//	Method prototypes
		static TemperatureSensorClass *init(const char *);
		static TemperatureSensorClass *instance();
		~TemperatureSensorClass();
		Tango::DbDatum	get_class_property(std::string &);
		Tango::DbDatum	get_default_device_property(std::string &);
		Tango::DbDatum	get_default_class_property(std::string &);

	protected:
		TemperatureSensorClass(std::string &);
		static TemperatureSensorClass *_instance;
		void command_factory();
		void attribute_factory(std::vector<Tango::Attr *> &);
		void pipe_factory();
		void write_class_property();
		void set_default_property();
		void get_class_property();
		std::string get_cvstag();
		std::string get_cvsroot();

	private:
		void device_factory(TANGO_UNUSED(const Tango::DevVarStringArray *));
		void create_static_attribute_list(std::vector<Tango::Attr *> &);
		void erase_dynamic_attributes(const Tango::DevVarStringArray *,std::vector<Tango::Attr *> &);
		std::vector<std::string>	defaultAttList;
		Tango::Attr *get_attr_object_by_name(std::vector<Tango::Attr *> &att_list, std::string attname);
};

}	//	End of namespace

#endif   //	TemperatureSensor_H
