/*----- PROTECTED REGION ID(TemperatureSensorStateMachine.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        TemperatureSensorStateMachine.cpp
//
// description : State machine file for the TemperatureSensor class
//
// project :     TemperatureSensor
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================

#include "TemperatureSensor.h"

/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	TemperatureSensor::TemperatureSensorStateMachine.cpp

//================================================================
//  States  |  Description
//================================================================
//  ON      |  Device is in normal operating state.
//  ALARM   |  Temperature is outside the alarm thresholds.


namespace TemperatureSensor_ns
{
//=================================================
//		Attributes Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method     : TemperatureSensor::is_Temperature_allowed()
 *	Description: Execution allowed for Temperature attribute
 */
//--------------------------------------------------------
bool TemperatureSensor::is_Temperature_allowed(TANGO_UNUSED(Tango::AttReqType type))
{

	//	Not any excluded states for Temperature attribute in read access.
	/*----- PROTECTED REGION ID(TemperatureSensor::TemperatureStateAllowed_READ) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	TemperatureSensor::TemperatureStateAllowed_READ
	return true;
}


//=================================================
//		Commands Allowed Methods
//=================================================

//--------------------------------------------------------
/**
 *	Method     : TemperatureSensor::is_Reset_allowed()
 *	Description: Execution allowed for Reset attribute
 */
//--------------------------------------------------------
bool TemperatureSensor::is_Reset_allowed(TANGO_UNUSED(const CORBA::Any &any))
{
	//	Not any excluded states for Reset command.
	/*----- PROTECTED REGION ID(TemperatureSensor::ResetStateAllowed) ENABLED START -----*/
	/* clang-format on */
	/* clang-format off */
	/*----- PROTECTED REGION END -----*/	//	TemperatureSensor::ResetStateAllowed
	return true;
}


/*----- PROTECTED REGION ID(TemperatureSensor::TemperatureSensorStateAllowed.AdditionalMethods) ENABLED START -----*/
/* clang-format on */
//	Additional Methods
/* clang-format off */
/*----- PROTECTED REGION END -----*/	//	TemperatureSensor::TemperatureSensorStateAllowed.AdditionalMethods

}	//	End of namespace
