/*----- PROTECTED REGION ID(TemperatureSensor.h) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        TemperatureSensor.h
//
// description : Include file for the TemperatureSensor class
//
// project :     TemperatureSensor
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#ifndef TemperatureSensor_H
#define TemperatureSensor_H

#include <tango/tango.h>
#include <thread>
#include <atomic>
#include <mutex>

/* clang-format off */
/*----- PROTECTED REGION END -----*/    //      TemperatureSensor.h

#ifdef TANGO_LOG
        // cppTango after c934adea (Merge branch 'remove-cout-definition' into 'main', 2022-05-23)
        // nothing to do
#else
        // cppTango 9.3-backports and older
        #define TANGO_LOG       cout
        #define TANGO_LOG_INFO  cout2
        #define TANGO_LOG_DEBUG cout3
#endif // TANGO_LOG

/**
 *  TemperatureSensor class description:
 *    A simulated temperature sensor -- C++ reimplementation of the Python TemperatureSensor from Lab 1.2, via Pogo.
 */


namespace TemperatureSensor_ns
{
/*----- PROTECTED REGION ID(TemperatureSensor::Additional Class Declarations) ENABLED START -----*/
/* clang-format on */
//      Additional Class Declarations
/* clang-format off */
/*----- PROTECTED REGION END -----*/    //      TemperatureSensor::Additional Class Declarations

class TemperatureSensor : public TANGO_BASE_CLASS
{

/*----- PROTECTED REGION ID(TemperatureSensor::Data Members) ENABLED START -----*/
/* clang-format on */
//      Add your own data members
private:
        std::thread        drift_thread;
        std::atomic<bool>  stop_thread{false};
        std::mutex         temperature_mutex;

        static constexpr double ALARM_MIN = 19.0;
        static constexpr double ALARM_MAX = 21.0;

        void drift_loop();
/* clang-format off */
/*----- PROTECTED REGION END -----*/    //      TemperatureSensor::Data Members


//      Attribute data members
public:
        Tango::DevDouble        *attr_Temperature_read;

//      Constructors and destructors
public:
        /**
         * Constructs a newly device object.
         *
         *      @param cl       Class.
         *      @param s        Device Name
         */
        TemperatureSensor(Tango::DeviceClass *cl,std::string &s);
        /**
         * Constructs a newly device object.
         *
         *      @param cl       Class.
         *      @param s        Device Name
         */
        TemperatureSensor(Tango::DeviceClass *cl,const char *s);
        /**
         * Constructs a newly device object.
         *
         *      @param cl       Class.
         *      @param s        Device name
         *      @param d        Device description.
         */
        TemperatureSensor(Tango::DeviceClass *cl,const char *s,const char *d);
        /**
         * The device object destructor.
         */
        ~TemperatureSensor();


//      Miscellaneous methods
public:
        /*
         *      will be called at device destruction or at init command.
         */
        void delete_device();
        /*
         *      Initialize the device
         */
        virtual void init_device();
        /*
         *      Always executed method before execution command method.
         */
        virtual void always_executed_hook();


//      Attribute methods
public:
        //--------------------------------------------------------
        /*
         *      Method     : TemperatureSensor::read_attr_hardware()
         *      Description: Hardware acquisition for attributes.
         */
        //--------------------------------------------------------
        virtual void read_attr_hardware(std::vector<long> &attr_list);

/**
 *      Attribute Temperature related methods
 *      Description: Simulated temperature reading, drifting via a background thread.
 *
 *      Data type:      Tango::DevDouble
 *      Attr type:      Scalar
 */
        virtual void read_Temperature(Tango::Attribute &attr);
        virtual bool is_Temperature_allowed(Tango::AttReqType type);


        //--------------------------------------------------------
        /**
         *      Method     : TemperatureSensor::add_dynamic_attributes()
         *      Description: Add dynamic attributes if any.
         */
        //--------------------------------------------------------
        void add_dynamic_attributes();




//      Command related methods
public:
        /**
         *      Command Reset related method
         *      Description: Reset the simulated temperature back to the baseline value (20.0 degC).
         *
         */
        virtual void reset();
        virtual bool is_Reset_allowed(const CORBA::Any &any);


        //--------------------------------------------------------
        /**
         *      Method     : TemperatureSensor::add_dynamic_commands()
         *      Description: Add dynamic commands if any.
         */
        //--------------------------------------------------------
        void add_dynamic_commands();

/*----- PROTECTED REGION ID(TemperatureSensor::Additional Method prototypes) ENABLED START -----*/
/* clang-format on */
//      Additional Method prototypes
/* clang-format off */
/*----- PROTECTED REGION END -----*/    //      TemperatureSensor::Additional Method prototypes
};

/*----- PROTECTED REGION ID(TemperatureSensor::Additional Classes Definitions) ENABLED START -----*/
/* clang-format on */
//      Additional Classes Definitions
/* clang-format off */
/*----- PROTECTED REGION END -----*/    //      TemperatureSensor::Additional Classes Definitions

}       //      End of namespace

#endif   //     TemperatureSensor_H
