/*----- PROTECTED REGION ID(TemperatureSensor.cpp) ENABLED START -----*/
/* clang-format on */
//=============================================================================
//
// file :        TemperatureSensor.cpp
//
// description : C++ source for the TemperatureSensor class and its commands.
//               The class is derived from Device. It represents the
//               CORBA servant object which will be accessed from the
//               network. All commands which can be executed on the
//               TemperatureSensor are implemented in this file.
//
// project :     TemperatureSensor
//
// This file is part of Tango device class.
//
// Tango is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Tango is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Tango.  If not, see <http://www.gnu.org/licenses/>.
//
//
//
//=============================================================================
//                This file is generated by POGO
//        (Program Obviously used to Generate tango Object)
//=============================================================================


#include "TemperatureSensor.h"
#include "TemperatureSensorClass.h"
#include <random>
#include <chrono>
/* clang-format off */
/*----- PROTECTED REGION END -----*/    //      TemperatureSensor.cpp

/**
 *  TemperatureSensor class description:
 *    A simulated temperature sensor -- C++ reimplementation of the Python TemperatureSensor from Lab 1.2, via Pogo.
 */

//================================================================
//  The following table gives the correspondence
//  between command and method names.
//
//  Command name  |  Method name
//================================================================
//  State         |  Inherited (no method)
//  Status        |  Inherited (no method)
//  Reset         |  reset
//================================================================

//================================================================
//  Attributes managed is:
//================================================================
//  Temperature  |  Tango::DevDouble    Scalar
//================================================================

namespace TemperatureSensor_ns
{
/*----- PROTECTED REGION ID(TemperatureSensor::namespace_starting) ENABLED START -----*/
/* clang-format on */
//      static initializations
constexpr double TemperatureSensor::ALARM_MIN;
constexpr double TemperatureSensor::ALARM_MAX;
/* clang-format off */
/*----- PROTECTED REGION END -----*/    //      TemperatureSensor::namespace_starting

//--------------------------------------------------------
/**
 *      Method     : TemperatureSensor::TemperatureSensor()
 *      Description: Constructors for a Tango device
 *                implementing the classTemperatureSensor
 */
//--------------------------------------------------------
TemperatureSensor::TemperatureSensor(Tango::DeviceClass *cl, std::string &s)
 : TANGO_BASE_CLASS(cl, s.c_str())
{
        /*----- PROTECTED REGION ID(TemperatureSensor::constructor_1) ENABLED START -----*/
        /* clang-format on */
        init_device();
        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::constructor_1
}
//--------------------------------------------------------
TemperatureSensor::TemperatureSensor(Tango::DeviceClass *cl, const char *s)
 : TANGO_BASE_CLASS(cl, s)
{
        /*----- PROTECTED REGION ID(TemperatureSensor::constructor_2) ENABLED START -----*/
        /* clang-format on */
        init_device();
        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::constructor_2
}
//--------------------------------------------------------
TemperatureSensor::TemperatureSensor(Tango::DeviceClass *cl, const char *s, const char *d)
 : TANGO_BASE_CLASS(cl, s, d)
{
        /*----- PROTECTED REGION ID(TemperatureSensor::constructor_3) ENABLED START -----*/
        /* clang-format on */
        init_device();
        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::constructor_3
}
//--------------------------------------------------------
TemperatureSensor::~TemperatureSensor()
{
        delete_device();
}

//--------------------------------------------------------
/**
 *      Method     : TemperatureSensor::delete_device()
 *      Description: will be called at device destruction or at init command
 */
//--------------------------------------------------------
void TemperatureSensor::delete_device()
{
        DEBUG_STREAM << "TemperatureSensor::delete_device() " << device_name << std::endl;
        /*----- PROTECTED REGION ID(TemperatureSensor::delete_device) ENABLED START -----*/
        /* clang-format on */
        //      Delete device allocated objects
        stop_thread = true;
        if (drift_thread.joinable())
        {
                drift_thread.join();
        }
        delete attr_Temperature_read;
        attr_Temperature_read = nullptr;
        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::delete_device
}

//--------------------------------------------------------
/**
 *      Method     : TemperatureSensor::init_device()
 *      Description: will be called at device initialization.
 */
//--------------------------------------------------------
void TemperatureSensor::init_device()
{
        DEBUG_STREAM << "TemperatureSensor::init_device() create device " << device_name << std::endl;
        /*----- PROTECTED REGION ID(TemperatureSensor::init_device_before) ENABLED START -----*/
        /* clang-format on */
        //      Initialization before get_device_property() call
        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::init_device_before

        //      No device property to be read from database

        /*----- PROTECTED REGION ID(TemperatureSensor::init_device) ENABLED START -----*/
        /* clang-format on */
        //      Initialize device
        attr_Temperature_read = new Tango::DevDouble;
        *attr_Temperature_read = 20.0;

        set_state(Tango::ON);

        stop_thread = false;
        drift_thread = std::thread(&TemperatureSensor::drift_loop, this);
        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::init_device
}


//--------------------------------------------------------
/**
 *      Method     : TemperatureSensor::always_executed_hook()
 *      Description: method always executed before any command is executed
 */
//--------------------------------------------------------
void TemperatureSensor::always_executed_hook()
{
        DEBUG_STREAM << "TemperatureSensor::always_executed_hook()  " << device_name << std::endl;
        /*----- PROTECTED REGION ID(TemperatureSensor::always_executed_hook) ENABLED START -----*/
        /* clang-format on */
        //      code always executed before all requests
        std::lock_guard<std::mutex> lock(temperature_mutex);
        if (*attr_Temperature_read < ALARM_MIN || *attr_Temperature_read > ALARM_MAX)
        {
                set_state(Tango::ALARM);
        }
        else
        {
                set_state(Tango::ON);
        }
        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::always_executed_hook
}

//--------------------------------------------------------
/**
 *      Method     : TemperatureSensor::read_attr_hardware()
 *      Description: Hardware acquisition for attributes
 */
//--------------------------------------------------------
void TemperatureSensor::read_attr_hardware(TANGO_UNUSED(std::vector<long> &attr_list))
{
        DEBUG_STREAM << "TemperatureSensor::read_attr_hardware(std::vector<long> &attr_list) entering... " << std::endl;
        /*----- PROTECTED REGION ID(TemperatureSensor::read_attr_hardware) ENABLED START -----*/
        /* clang-format on */
        //      Add your own code
        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::read_attr_hardware
}

//--------------------------------------------------------
/**
 *      Read attribute Temperature related method
 *      Description: Simulated temperature reading, drifting via a background thread.
 *
 *      Data type:      Tango::DevDouble
 *      Attr type:      Scalar
 */
//--------------------------------------------------------
void TemperatureSensor::read_Temperature(Tango::Attribute &attr)
{
        DEBUG_STREAM << "TemperatureSensor::read_Temperature(Tango::Attribute &attr) entering... " << std::endl;
        /*----- PROTECTED REGION ID(TemperatureSensor::read_Temperature) ENABLED START -----*/
        /* clang-format on */
        //      Set the attribute value
        std::lock_guard<std::mutex> lock(temperature_mutex);
        attr.set_value(attr_Temperature_read);
        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::read_Temperature
}

//--------------------------------------------------------
/**
 *      Method     : TemperatureSensor::add_dynamic_attributes()
 *      Description: Create the dynamic attributes if any
 *                for specified device.
 */
//--------------------------------------------------------
void TemperatureSensor::add_dynamic_attributes()
{
        /*----- PROTECTED REGION ID(TemperatureSensor::add_dynamic_attributes) ENABLED START -----*/
        /* clang-format on */
        //      Add your own code to create and add dynamic attributes if any
        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::add_dynamic_attributes
}

//--------------------------------------------------------
/**
 *      Command Reset related method
 *      Description: Reset the simulated temperature back to the baseline value (20.0 degC).
 *
 */
//--------------------------------------------------------
void TemperatureSensor::reset()
{
        DEBUG_STREAM << "TemperatureSensor::Reset()  - " << device_name << std::endl;
        /*----- PROTECTED REGION ID(TemperatureSensor::reset) ENABLED START -----*/
        /* clang-format on */

        std::lock_guard<std::mutex> lock(temperature_mutex);
        *attr_Temperature_read = 20.0;

        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::reset
}
//--------------------------------------------------------
/**
 *      Method     : TemperatureSensor::add_dynamic_commands()
 *      Description: Create the dynamic commands if any
 *                for specified device.
 */
//--------------------------------------------------------
void TemperatureSensor::add_dynamic_commands()
{
        /*----- PROTECTED REGION ID(TemperatureSensor::add_dynamic_commands) ENABLED START -----*/
        /* clang-format on */
        //      Add your own code to create and add dynamic commands if any
        /* clang-format off */
        /*----- PROTECTED REGION END -----*/    //      TemperatureSensor::add_dynamic_commands
}

/*----- PROTECTED REGION ID(TemperatureSensor::namespace_ending) ENABLED START -----*/
/* clang-format on */
//      Additional Methods
void TemperatureSensor::drift_loop()
{
        std::random_device rd;
        std::mt19937 gen(rd());
        std::uniform_real_distribution<double> step(-0.5, 0.5);

        while (!stop_thread)
        {
                {
                        std::lock_guard<std::mutex> lock(temperature_mutex);
                        *attr_Temperature_read += step(gen);
                }
                std::this_thread::sleep_for(std::chrono::seconds(1));
        }
}
/* clang-format off */
/*----- PROTECTED REGION END -----*/    //      TemperatureSensor::namespace_ending
} //    namespace
